----------------------------------------------------------------------------------
-- Company: Center for Industrial Electronics - Syddansk Universitet
-- Engineer: Robert Brehm
-- 
-- Create Date: 03/02/2021 08:37:28 AM
-- Design Name: 
-- Module Name: mips - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity control_unit is
    port (
        opcode: in std_logic_vector(5 downto 0);
        rst: in std_logic;
        alu_op: out std_logic_vector(1 downto 0);
        reg_write: out std_logic;
        dr_select: out std_logic;
        reg_or_imm: out std_logic;
        pc_select: out std_logic_vector(1 downto 0);
        mem_wrt_en: out std_logic;
        alu_or_mem: out std_logic
    );
end control_unit;

architecture Behavioral of control_unit is

begin

    process(rst,opcode)
    begin
        if(rst = '1') then
            alu_op <= "00";         -- Determines the ALU operation --> connected to mips_alu_op). 
                                    -- See the ALU control bits as a function of ALUop bits and opcode bits table.
            reg_write <= '0';       -- Controls write access to the register bank --> mips_reg_file
            dr_select <= '0';       -- Controls whether destination register is numbered from isntruction[20-16] or instruction[15-11] 
            reg_or_imm <= '0';      -- Controls if teh ALU input B is an immediate (then instruction[15-0]) or is 
                                    -- Sourced from the register bank (source register 2)
            pc_select <= "00";      -- Selects the PC brnaching control multiplexer
            mem_wrt_en <= '0';      -- Enables data memory write
            alu_or_mem <= '0';      -- Determines if the destination register is sourced from teh ALU or the memory data output port.
        else 
            case opcode is
                when "000000" =>            -- add            
--                    TO BE COMPLETED BY STUDENT
--                    alu_op <= ...
--                    reg_write <= ...   
--                    dr_select <= ...         
--                    reg_or_imm <= ...         
--                    pc_select <= ...   
--                    mem_wrt_en <= ...   
--                    alu_or_mem <= ...   
                    
                when "001000" =>            -- addi
--                    TO BE COMPLETED BY STUDENT
--                    alu_op <= ...
--                    reg_write <= ...   
--                    dr_select <= ...         
--                    reg_or_imm <= ...         
--                    pc_select <= ...   
--                    mem_wrt_en <= ...   
--                    alu_or_mem <= ...   
                when "000010" =>            --jump
--                    TO BE COMPLETED BY STUDENT
--                    alu_op <= ...
--                    reg_write <= ...   
--                    dr_select <= ...         
--                    reg_or_imm <= ...         
--                    pc_select <= ...   
--                    mem_wrt_en <= ...   
--                    alu_or_mem <= ...   
                    
                when "000100" =>            --beq
--                    TO BE COMPLETED BY STUDENT
--                    alu_op <= ...
--                    reg_write <= ...   
--                    dr_select <= ...         
--                    reg_or_imm <= ...         
--                    pc_select <= ...   
--                    mem_wrt_en <= ...   
--                    alu_or_mem <= ...   

                when "101011" =>            --sw
--                    TO BE COMPLETED BY STUDENT
--                    alu_op <= ...
--                    reg_write <= ...   
--                    dr_select <= ...         
--                    reg_or_imm <= ...         
--                    pc_select <= ...   
--                    mem_wrt_en <= ...   
--                    alu_or_mem <= ...   

                when "100011" =>            --lw
--                    TO BE COMPLETED BY STUDENT
--                    alu_op <= ...
--                    reg_write <= ...   
--                    dr_select <= ...         
--                    reg_or_imm <= ...         
--                    pc_select <= ...   
--                    mem_wrt_en <= ...   
--                    alu_or_mem <= ...   

                when others =>
                    alu_op <= "00";
                    reg_write <= '0';
                    dr_select <= '0';
                    reg_or_imm <= '0';
                    pc_select <= "00";
                    mem_wrt_en <= '0';
                    alu_or_mem <= '0';

            end case;
       end if;
   end process;
end Behavioral;
