#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Mar 22 13:51:29 CET 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 4ac812106ae3447285fa876084d4a0fc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mips_tb_behav xil_defaultlib.mips_tb -log elaborate.log"
xelab -wto 4ac812106ae3447285fa876084d4a0fc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mips_tb_behav xil_defaultlib.mips_tb -log elaborate.log

